#!/bin/sh

if [ -x /usr/lib/update-notifier/update-motd-updates-available ]; then
    echo -n "\033[31m"
    exec /usr/lib/update-notifier/update-motd-updates-available | sed 's/^/  /'
    echo -n "\033[0m"
fi
