#!/bin/sh

# if the current release is under development there won't be a new one
if [ "$(lsb_release -sd | cut -d' ' -f4)" = "(development" ]; then
    exit 0
fi
if [ -x /usr/lib/ubuntu-release-upgrader/release-upgrade-motd ]; then
    echo -n "\033[33m"
    exec /usr/lib/ubuntu-release-upgrader/release-upgrade-motd | sed 's/^/  /g'
    echo -n "\033[0m"
fi
